// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NovaCategoria struct {
	Nome      string  `json:"nome"`
	Descricao *string `json:"descricao,omitempty"`
}

type NovoCurso struct {
	Nome        string `json:"nome"`
	Descricao   string `json:"descricao"`
	IDCategoria string `json:"idCategoria"`
}

type Query struct {
}
