// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Categoria struct {
	ID        string   `json:"id"`
	Nome      string   `json:"nome"`
	Descricao *string  `json:"descricao,omitempty"`
	Cursos    []*Curso `json:"cursos"`
}

type Curso struct {
	ID        string     `json:"id"`
	Nome      string     `json:"nome"`
	Descricao *string    `json:"descricao,omitempty"`
	Categoria *Categoria `json:"categoria"`
}

type Mutation struct {
}

type NovaCategoria struct {
	Nome      string  `json:"nome"`
	Descricao *string `json:"descricao,omitempty"`
}

type NovoCurso struct {
	Nome        string `json:"nome"`
	Descricao   string `json:"descricao"`
	IDCategoria string `json:"idCategoria"`
}

type Query struct {
}
